import { create } from "zustand";
import { persist } from "zustand/middleware";
import { mockReport, generateScanId } from "../lib/mockData";

const useScanStore = create(
  persist(
    (set, get) => ({
      // ── Current session ──────────────────────────────────────────────────
      currentScan: null,   // { id, name, previewUrl, size, type }
      currentAnalysis: null,   // { findings, overall_risk, scan_type, heatmap_base64 }
      currentReport: null,   // RADLEX report object
      isAnalyzing: false,

      // ── History (persisted) ──────────────────────────────────────────────
      history: [],

      // ── Setters ──────────────────────────────────────────────────────────
      setCurrentScan: (scan) => set({ currentScan: scan }),

      setCurrentAnalysis: (analysis) => {
        // Build sections from real backend response or mock
        const findings = analysis?.findings ?? [];

        const findingsText = findings.length > 0
          ? findings.map((f, i) =>
            `${i + 1}. ${f.label ?? f.name} — Confidence: ${Math.round((f.confidence ?? 0) * 100)}%, Uncertainty: ${f.uncertainty ?? 'N/A'}`
          ).join('\n')
          : mockReport.sections.find(s => s.id === 'findings')?.content ?? '';

        const impressionText = findings.length > 0
          ? findings
            .filter(f => (f.confidence ?? 0) > 0.5)
            .map((f, i) =>
              `${i + 1}. ${f.label ?? f.name} detected (confidence: ${Math.round((f.confidence ?? 0) * 100)}%).`
            ).join('\n')
          : mockReport.sections.find(s => s.id === 'impression')?.content ?? '';

        const autoReport = {
          ...mockReport,
          id: generateScanId(),
          scan_type: analysis?.scan_type ?? 'Chest X-ray',
          overall_risk: analysis?.overall_risk ?? 'MODERATE',
          generated_at: new Date().toISOString(),
          sections: [
            {
              id: 'clinical_indication',
              title: 'Clinical Indication',
              content: mockReport.sections.find(s => s.id === 'clinical_indication')?.content ?? '',
            },
            {
              id: 'technique',
              title: 'Technique',
              content: mockReport.sections.find(s => s.id === 'technique')?.content ?? '',
            },
            {
              id: 'findings',
              title: 'Findings',
              content: findingsText,
            },
            {
              id: 'impression',
              title: 'Impression',
              content: impressionText,
            },
            {
              id: 'recommendation',
              title: 'Recommendation',
              content: mockReport.sections.find(s => s.id === 'recommendation')?.content ?? '',
            },
            {
              id: 'disclaimer',
              title: 'AI Disclaimer',
              content: 'This report was generated by ClearScan AI (DenseNet-121, NIH ChestX-ray14). All findings require review and approval by a licensed radiologist before clinical use.',
            },
          ],
        };
        set({ currentAnalysis: analysis, currentReport: autoReport });
      },

      setCurrentReport: (report) => set({ currentReport: report }),
      setIsAnalyzing: (val) => set({ isAnalyzing: val }),

      // ── Clear current session (does NOT wipe history) ────────────────────
      clearCurrentScan: () => set({
        currentScan: null,
        currentAnalysis: null,
        currentReport: null,
        isAnalyzing: false,
      }),

      // ── History actions ──────────────────────────────────────────────────
      addToHistory: (scan) => {
        const existing = get().history;
        // Prevent duplicates by ID
        if (existing.find((s) => s.id === scan.id)) return;
        set({ history: [scan, ...existing].slice(0, 50) }); // cap at 50
      },

      removeFromHistory: (id) =>
        set({ history: get().history.filter((s) => s.id !== id) }),

      clearHistory: () => set({ history: [] }),
    }),
    {
      name: "clearscan-store",
      // Only persist history — session data (currentScan etc.) resets on reload
      partialize: (state) => ({ history: state.history }),
    }
  )
);

export default useScanStore;

