import { useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import {
  FileText, Download, ArrowLeft, Printer,
  RotateCcw, CheckCircle2, Activity,
} from "lucide-react";
import toast from "react-hot-toast";
import useScanStore from "../store/useScanStore";
import { mockReport, mockAnalysis } from "../lib/mockData";
import { cn, getRiskBadgeClasses, formatConfidence } from "../lib/utils";
import ReportSection from "../components/ReportSection";
import ReportMetaBar from "../components/ReportMetaBar";

// ─── Empty state ─────────────────────────────────────────────────────────────
function EmptyState() {
  const navigate = useNavigate();
  return (
    <div className="min-h-[60vh] flex items-center justify-center px-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="text-center max-w-sm"
      >
        <div className="mx-auto mb-5 w-16 h-16 rounded-2xl bg-slate-800 border border-slate-700 flex items-center justify-center">
          <FileText size={28} className="text-slate-500" />
        </div>
        <h2 className="text-xl font-semibold text-slate-100 mb-2">No report available</h2>
        <p className="text-slate-400 text-sm mb-6 leading-relaxed">
          Run an AI analysis first, then come back here to review and export the full clinical report.
        </p>
        <motion.button
          whileHover={{ scale: 1.04 }}
          whileTap={{ scale: 0.97 }}
          onClick={() => navigate("/")}
          className="inline-flex items-center gap-2 bg-blue-500 hover:bg-blue-400 text-white font-semibold px-5 py-2.5 rounded-lg transition-colors"
        >
          <Activity size={16} />
          Upload a scan
        </motion.button>
      </motion.div>
    </div>
  );
}

// ─── PDF export helper ────────────────────────────────────────────────────────
async function exportToPDF(reportData, sections) {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW  = doc.internal.pageSize.getWidth();
  const margin = 18;
  const col    = pageW - margin * 2;
  let y        = margin;

  // ── Header ──
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageW, 28, "F");
  doc.setFontSize(16);
  doc.setTextColor(241, 245, 249);
  doc.setFont("helvetica", "bold");
  doc.text("ClearScan AI — Diagnostic Report", margin, 17);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text(`RADLEX v4.1  ·  ${reportData.scan_type ?? "Chest X-Ray"}  ·  ${reportData.id ?? "RPT-0001"}`, margin, 24);
  y = 38;

  // ── Overall risk ──
  const riskColors = {
    LOW: [34, 197, 94], MEDIUM: [245, 158, 11],
    HIGH: [239, 68, 68], CRITICAL: [220, 38, 38],
  };
  const rc = riskColors[reportData.overall_risk] ?? [59, 130, 246];
  doc.setFillColor(...rc);
  doc.roundedRect(margin, y, col, 10, 2, 2, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(`Overall Risk: ${reportData.overall_risk ?? "—"}`, margin + 4, y + 7);
  y += 16;

  // ── Sections ──
  sections.forEach((s) => {
    if (y > 260) { doc.addPage(); y = margin; }

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(148, 163, 184);
    doc.text(s.title.toUpperCase(), margin, y);
    y += 5;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 41, 59);

    // Draw section background
    const lines = doc.splitTextToSize(s.content, col - 6);
    const boxH  = lines.length * 5 + 6;
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, col, boxH, 2, 2, "F");
    doc.setTextColor(30, 41, 59);
    doc.text(lines, margin + 3, y + 5);
    y += boxH + 6;
  });

  // ── Footer ──
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "Generated by ClearScan AI · For clinical use only · Not a substitute for professional radiological review",
    margin,
    doc.internal.pageSize.getHeight() - 8
  );

  doc.save(`ClearScan-Report-${reportData.id ?? "export"}.pdf`);
}

// ─── Main page ───────────────────────────────────────────────────────────────
export default function ReportPage() {
  const navigate        = useNavigate();
  const storedReport    = useScanStore((s) => s.currentReport);
  const storedAnalysis  = useScanStore((s) => s.currentAnalysis);
  const setCurrentReport = useScanStore((s) => s.setCurrentReport);

  const analysis  = storedAnalysis ?? mockAnalysis;
  const baseReport = storedReport ?? mockReport;

  // Local editable sections state
  const [sections, setSections] = useState(
    () => baseReport.sections?.map((s) => ({ ...s })) ?? []
  );
  const [exporting, setExporting] = useState(false);
  const [printed,   setPrinted]   = useState(false);

  if (!storedReport && !storedAnalysis) {
    return <EmptyState />;
  }

  function handleSectionUpdate(id, newContent) {
    setSections((prev) =>
      prev.map((s) => (s.id === id ? { ...s, content: newContent } : s))
    );
    toast.success("Section updated");
  }

  function handleReset() {
    setSections(baseReport.sections?.map((s) => ({ ...s })) ?? []);
    toast("Report reset to original", { icon: "↩️" });
  }

  async function handleExportPDF() {
    setExporting(true);
    try {
      await exportToPDF(
        { ...baseReport, overall_risk: analysis.overall_risk },
        sections
      );
      toast.success("PDF exported successfully");
    } catch (err) {
      toast.error("Export failed — check console");
      console.error(err);
    } finally {
      setExporting(false);
    }
  }

  function handlePrint() {
    window.print();
    setPrinted(true);
    setTimeout(() => setPrinted(false), 2500);
  }

  return (
    <div className="min-h-screen px-4 sm:px-6 lg:px-8 py-8 max-w-7xl mx-auto">
      {/* ── Page header ── */}
      <motion.div
        initial={{ opacity: 0, y: -12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35 }}
        className="mb-8"
      >
        <button
          onClick={() => navigate("/results")}
          className="flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-300 mb-3 transition-colors font-mono uppercase tracking-wider"
        >
          <ArrowLeft size={12} /> Back to results
        </button>
        <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-slate-100">Report Editor</h1>
            <p className="text-slate-400 mt-1 text-sm">
              Review, edit, and export the RADLEX-structured diagnostic report
            </p>
          </div>
          {/* Action buttons */}
          <div className="flex items-center gap-2 flex-wrap">
            <motion.button
              whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
              onClick={handleReset}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 hover:bg-slate-700 text-slate-300 text-sm transition-colors"
            >
              <RotateCcw size={14} /> Reset
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 hover:bg-slate-700 text-slate-300 text-sm transition-colors"
            >
              {printed ? <CheckCircle2 size={14} className="text-green-400" /> : <Printer size={14} />}
              Print
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
              onClick={handleExportPDF}
              disabled={exporting}
              className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-blue-500 hover:bg-blue-400 disabled:opacity-60 text-white font-semibold text-sm transition-colors shadow-glow-blue"
            >
              <Download size={14} className={exporting ? "animate-bounce" : ""} />
              {exporting ? "Exporting…" : "Export PDF"}
            </motion.button>
          </div>
        </div>
      </motion.div>

      {/* ── Main layout ── */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">

        {/* ── LEFT: editable report (3/4) ── */}
        <div className="lg:col-span-3 flex flex-col gap-4">
          {/* Meta bar */}
          <ReportMetaBar report={{ ...baseReport, overall_risk: analysis.overall_risk }} />

          {/* Sections */}
          {sections.map((section, i) => (
            <ReportSection
              key={section.id}
              section={section}
              index={i}
              onUpdate={handleSectionUpdate}
            />
          ))}

          {/* Bottom export nudge */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: sections.length * 0.08 + 0.3 }}
            className="rounded-xl border border-dashed border-slate-700 p-5 text-center"
          >
            <p className="text-slate-500 text-sm mb-3">All sections reviewed? Export the final report.</p>
            <motion.button
              whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
              onClick={handleExportPDF}
              disabled={exporting}
              className="inline-flex items-center gap-2 bg-blue-500 hover:bg-blue-400 disabled:opacity-60 text-white font-semibold px-5 py-2.5 rounded-lg transition-colors text-sm"
            >
              <Download size={15} />
              {exporting ? "Exporting…" : "Export PDF"}
            </motion.button>
          </motion.div>
        </div>

        {/* ── RIGHT: sidebar summary (1/4) ── */}
        <div className="lg:col-span-1">
          <div className="lg:sticky lg:top-24 flex flex-col gap-4">

            {/* Overall risk */}
            <motion.div
              initial={{ opacity: 0, x: 16 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.4, delay: 0.1 }}
              className="rounded-xl bg-bg-surface border border-slate-700 shadow-card p-4"
            >
              <p className="text-xs text-slate-500 uppercase tracking-widest mb-3 font-mono">Summary</p>
              <div className={cn(
                "text-center py-3 rounded-lg border font-bold text-lg mb-3",
                getRiskBadgeClasses(analysis.overall_risk)
              )}>
                {analysis.overall_risk}
              </div>
              <p className="text-xs text-slate-500 text-center">Overall risk level</p>
            </motion.div>

            {/* Findings mini list */}
            <motion.div
              initial={{ opacity: 0, x: 16 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.4, delay: 0.18 }}
              className="rounded-xl bg-bg-surface border border-slate-700 shadow-card p-4"
            >
              <p className="text-xs text-slate-500 uppercase tracking-widest mb-3 font-mono">Findings</p>
              <div className="flex flex-col gap-2">
                {analysis.findings.map((f) => (
                  <div key={f.name} className="flex items-center justify-between gap-2">
                    <span className="text-xs text-slate-300 truncate">{f.name}</span>
                    <div className="flex items-center gap-1.5 shrink-0">
                      <span className="text-xs font-mono text-slate-400">{formatConfidence(f.confidence)}</span>
                      <span className={cn("text-[10px] font-semibold px-1.5 py-0.5 rounded-full", getRiskBadgeClasses(f.risk_level))}>
                        {f.risk_level}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>

            {/* Sections checklist */}
            <motion.div
              initial={{ opacity: 0, x: 16 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.4, delay: 0.26 }}
              className="rounded-xl bg-bg-surface border border-slate-700 shadow-card p-4"
            >
              <p className="text-xs text-slate-500 uppercase tracking-widest mb-3 font-mono">Sections</p>
              <div className="flex flex-col gap-1.5">
                {sections.map((s) => (
                  <div key={s.id} className="flex items-center gap-2 text-xs text-slate-400">
                    <CheckCircle2 size={12} className="text-green-500 shrink-0" />
                    {s.title}
                  </div>
                ))}
              </div>
            </motion.div>

          </div>
        </div>
      </div>
    </div>
  );
}

