import AnalyzingOverlay from "../components/AnalyzingOverlay";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { Cpu, Zap, WifiOff, ShieldCheck } from "lucide-react";
import toast from "react-hot-toast";
import useScanStore from "../store/useScanStore";
import { generateScanId } from "../lib/mockData";
import UploadDropZone from "../components/UploadDropZone";
import RecentScansSidebar from "../components/RecentScansSidebar";
import StatPill from "../components/StatPill";

const API_BASE = import.meta.env.VITE_API_BASE_URL ||
  'https://clearscan-backend-naxgdcywoa-el.a.run.app';

export default function UploadPage() {
  const navigate = useNavigate();
  const setCurrentScan = useScanStore((s) => s.setCurrentScan);
  const setCurrentAnalysis = useScanStore((s) => s.setCurrentAnalysis);
  const setCurrentReport = useScanStore((s) => s.setCurrentReport);
  const setIsAnalyzing = useScanStore((s) => s.setIsAnalyzing);
  const addToHistory = useScanStore((s) => s.addToHistory);
  const isAnalyzing = useScanStore((s) => s.isAnalyzing);

  const [pendingFile, setPendingFile] = useState(null);

  function handleFileAccepted(fileData) {
    setPendingFile(fileData);
  }

  function handleClear() {
    setPendingFile(null);
  }

  async function handleAnalyze() {
    if (!pendingFile) return;

    const scanId = generateScanId();

    setCurrentScan({
      id: scanId,
      name: pendingFile.name,
      previewUrl: pendingFile.previewUrl,
      size: pendingFile.size,
      type: pendingFile.type,
    });

    setIsAnalyzing(true);

    try {
      // ── Step 1: Call /analyse with real image ──────────────────────────
      const formData = new FormData();
      formData.append('image', pendingFile.file);
      formData.append('metadata', JSON.stringify({
        patient_id: scanId,
        scan_type: 'Chest X-ray',
      }));

      toast.loading('Analysing scan with AI...', { id: 'analyse' });

      const analyseRes = await fetch(`${API_BASE}/analyse`, {
        method: 'POST',
        body: formData,
      });

      if (!analyseRes.ok) throw new Error('Analysis failed');
      const analyseData = await analyseRes.json();
      toast.dismiss('analyse');

      // ── Step 2: Call /report with real findings ────────────────────────
      toast.loading('Generating report with Gemini...', { id: 'report' });

      const reportRes = await fetch(`${API_BASE}/report`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          findings: analyseData.findings,
          metadata: {
            patient_id: scanId,
            scan_type: 'Chest X-ray',
          },
          scan_date: new Date().toISOString().split('T')[0],
        }),
      });

      if (!reportRes.ok) throw new Error('Report generation failed');
      const reportData = await reportRes.json();
      toast.dismiss('report');

      // ── Step 3: Build analysis object from real data ───────────────────
      const realAnalysis = {
        findings: analyseData.findings.map(f => ({
          name: f.label,
          label: f.label,
          confidence: f.confidence,
          uncertainty: f.uncertainty,
          risk_level: f.confidence > 0.7 ? 'HIGH' :
            f.confidence > 0.4 ? 'MEDIUM' : 'LOW',
        })),
        overall_risk: analyseData.risk_level,
        heatmap_base64: analyseData.heatmap_base64,
        scan_type: 'Chest X-ray',
        analyzed_at: new Date().toISOString(),
        model_version: analyseData.model_version,
      };

      // ── Step 4: Build report sections from Gemini response ─────────────
      const draft = reportData.draft;
      const realReport = {
        id: scanId,
        scan_type: 'Chest X-ray',
        overall_risk: analyseData.risk_level,
        generated_at: new Date().toISOString(),
        is_fallback: reportData.is_fallback,
        sections: [
          {
            id: 'clinical_indication',
            title: 'Clinical Indication',
            content: draft.indication,
          },
          {
            id: 'technique',
            title: 'Technique',
            content: draft.technique,
          },
          {
            id: 'findings',
            title: 'Findings',
            content: draft.findings,
          },
          {
            id: 'impression',
            title: 'Impression',
            content: draft.impression,
          },
          {
            id: 'recommendation',
            title: 'Recommendation',
            content: draft.recommendation,
          },
          {
            id: 'disclaimer',
            title: 'AI Disclaimer',
            content: draft.disclaimer ||
              'This report was generated by ClearScan AI (DenseNet-121, NIH ChestX-ray14). ' +
              'All findings require review and approval by a licensed radiologist before clinical use.',
          },
        ],
      };

      // ── Step 5: Save to store ──────────────────────────────────────────
      setCurrentAnalysis(realAnalysis);
      setCurrentReport(realReport);

      addToHistory({
        id: scanId,
        scan_type: realAnalysis.scan_type,
        overall_risk: realAnalysis.overall_risk,
        findings: realAnalysis.findings,
        date: new Date().toISOString(),
        previewUrl: pendingFile.previewUrl,
      });

      toast.success('Analysis complete ✅');
      navigate('/results');

    } catch (err) {
      console.error(err);
      toast.dismiss('analyse');
      toast.dismiss('report');
      toast.error(`Failed: ${err.message}`);
    } finally {
      setIsAnalyzing(false);
    }
  }

  return (
    <div className="min-h-screen px-4 sm:px-6 lg:px-8 py-12 max-w-7xl mx-auto">

      {/* ── Hero ── */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45 }}
        className="mb-10 text-center"
      >
        <span className="inline-flex items-center gap-2 bg-blue-500/10 border border-blue-500/30 text-blue-400 text-xs font-semibold px-3 py-1.5 rounded-full mb-5 uppercase tracking-widest">
          <Cpu size={12} />
          AI-Powered Diagnostic Imaging
        </span>
        <h1 className="text-4xl sm:text-5xl font-bold text-slate-100 leading-tight mb-4">
          Radiological findings,{" "}
          <span className="text-blue-400">in seconds</span>
        </h1>
        <p className="text-slate-400 text-base sm:text-lg max-w-xl mx-auto leading-relaxed">
          Upload a chest X-ray or CT scan. ClearScan AI detects pathologies,
          generates Grad-CAM heatmaps, and produces a RADLEX-structured report —
          entirely offline.
        </p>
      </motion.div>

      {/* ── Stat pills ── */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, delay: 0.1 }}
        className="flex flex-wrap justify-center gap-3 mb-10"
      >
        <StatPill icon={Cpu} value="14+" label="Pathologies detected" />
        <StatPill icon={Zap} value="<2s" label="Avg. analysis time" />
        <StatPill icon={WifiOff} value="100%" label="Offline capable" />
        <StatPill icon={ShieldCheck} value="HIPAA" label="Privacy-aware" />
      </motion.div>

      {/* ── Main layout ── */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <motion.div
          initial={{ opacity: 0, x: -16 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.45, delay: 0.15 }}
          className="lg:col-span-2"
        >
          <UploadDropZone
            onFileAccepted={handleFileAccepted}
            currentScan={pendingFile}
            onClear={handleClear}
            onAnalyze={handleAnalyze}
            isAnalyzing={isAnalyzing}
          />
        </motion.div>
        <motion.div
          initial={{ opacity: 0, x: 16 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.45, delay: 0.2 }}
          className="lg:col-span-1"
        >
          <RecentScansSidebar />
        </motion.div>
      </div>

      <AnalyzingOverlay visible={isAnalyzing} />
    </div>
  );
}